# Generated by Django 3.1.2 on 2020-10-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='image',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
